global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:9090

# This job is what will pull metrics from app
- job_name: app
  scrape_interval: 5s
  honor_timestamps: true  
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - docker.for.mac.host.internal:3030 # Used to connect from container to a port on host

# This scraper will pull metrics from the Node Exporter
# It contains metrics from the OS
- job_name: node
  scrape_interval: 10s
  static_configs:
  - targets: ['docker.for.mac.host.internal:9100']