{
 "title": "App Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "HTTP_STATUS_CODE",
    "label": "Status Code",
    "query": {
     "query": "label_values(app_requests_total, statusCode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_requests_total[$__interval]))"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_usuarios_logados_total" }
   ]
  },
  {
   "title": "Requests error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_requests_total{statusCode=\"500\"}[1m])) / sum(rate(app_requests_total[1m]))",
     "legendFormat": "% HTTP 500"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 } },
  {
   "title": "AVG Request Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_duration_seconds_bucket[15s])) by (le))",
     "legendFormat": "Rate of 95%"
    },
    {
     "expr": "histogram_quantile(0.85, sum(rate(app_request_duration_seconds_bucket[15s])) by (le))",
     "legendFormat": "Rate of 85%"
    }
   ]
  },
  {
   "title": "Requests rate by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_requests_total{statusCode=~\"$HTTP_STATUS_CODE\"}[15s])) by (statusCode)",
     "legendFormat": "Status Code $HTTP_STATUS_CODE"
    }
   ]
  }
 ]
}